import { WIDTHSCALESIZE, HEIGHTSCALESIZE } from './mixins';

//widths and heights
export const WIDTH_SCALE_300 = WIDTHSCALESIZE(300);
export const WIDTH_SCALE_280 = WIDTHSCALESIZE(280);
export const WIDTH_SCALE_150 = WIDTHSCALESIZE(150);
export const WIDTH_SCALE_135 = WIDTHSCALESIZE(135);
export const ICON_BUTTON_WIDTH = WIDTHSCALESIZE(100);
export const HEADER_MAIN_BUTTON_WIDTH = WIDTHSCALESIZE(140);
export const WIDTH_SCALE_50 = WIDTHSCALESIZE(50);
export const SWITCH_WIDTH = HEIGHTSCALESIZE(30);
export const HEIGHT_BUTTON = HEIGHTSCALESIZE(8) * 3;
export const HEIGHT_SHOW_DATE = HEIGHTSCALESIZE(9) * 2;
export const HEIGHT_ALARM = HEIGHTSCALESIZE(8) * 5;
export const HEIGHT_PHRASES_CONTAINER = HEIGHTSCALESIZE(14) * 7;
export const SEARCHBAR_WIDTH = WIDTHSCALESIZE(180);
export const SEARCHBAR_HEIGHT = HEIGHTSCALESIZE(20);
export const FILTER_COMPONENT_HEIGHT = HEIGHTSCALESIZE(20);
export const CUSTOM_HEADER_HEIGHT = HEIGHTSCALESIZE(30);

//margins and paddings and radius
export const ALARM_MARGIN = WIDTHSCALESIZE(40);
export const MARGIN_1 = HEIGHTSCALESIZE(5);
export const MARGIN_3 = HEIGHTSCALESIZE(8);
export const MARGIN_4 = HEIGHTSCALESIZE(80);
export const MARGIN_5 = HEIGHTSCALESIZE(70);
export const CHIP_MARGIN = HEIGHTSCALESIZE(4);
export const SWITCH_PADDING = HEIGHTSCALESIZE(2);
export const BORDER_RADIUS_8 = WIDTHSCALESIZE(8);
export const WALLET_DONE_RADIUS = HEIGHTSCALESIZE(40);
export const SWITCH_RADIUS = HEIGHTSCALESIZE(10);
export const MARGIN_2 = HEIGHTSCALESIZE(8) * 3;
export const HEADER_MAIN_BUTTON_PADDING = WIDTHSCALESIZE(40);
export const HEADER_MAIN_PADDING = WIDTHSCALESIZE(20);
export const FILTER_MODAL_PADDING = WIDTHSCALESIZE(20);
export const DATE_PICKER_PADDING = WIDTHSCALESIZE(13);
export const TRANSACTION_CARD_PADDING = HEIGHTSCALESIZE(3);
export const SEARCHBAR_LEFT_PADDING = HEIGHTSCALESIZE(4);
export const SEARCHBAR_RIGHT_PADDING = HEIGHTSCALESIZE(9);
export const SEARCHBAR_TOP_PADDING = HEIGHTSCALESIZE(4);

//sizes
export const ICON_SIZE = WIDTHSCALESIZE(25);
export const QRCODE_SIZE = WIDTHSCALESIZE(270);
export const DROP_DOWN_ICON_SIZE = WIDTHSCALESIZE(18);
export const CHECKBOX_SIZE = HEIGHTSCALESIZE(4) * 2;
export const IMAGE_SIZE = HEIGHTSCALESIZE(70) * 1.8;
export const SEARCH_IMAGE_SIZE = HEIGHTSCALESIZE(70)*1.5;
export const INDICATOR_ICON_SIZE = WIDTHSCALESIZE(50);
export const SEARCH_ICON_SIZE = WIDTHSCALESIZE(18);


